Added `stopRelease()` feature, test, prettier
Azuro-protocol/AirDrop pull request #6
Opened 2024-03-04 18:57 UTC by KiselevMaxim

2024-03-05 12:11 UTC, Shchepetov requested changes

2024-03-05 12:11 UTC, Shchepetov commented on .vscode/settings.json
> +}
Add to .gitignore

2024-03-05 12:35 UTC, KiselevMaxim commented on .vscode/settings.json
> +}
fixed

2024-03-07 06:18 UTC, Shchepetov approved these changes

2024-03-07 07:46 UTC, merged